### ISSUE TITLE
Use separate CSS file

### ISSUE THREAD

**Issue by silsha** [silsha/fnordcredit#135]
All die CSS-Regeln sind aktuell inline für die einzelnen Elemente gesetzt, z.B.
```html
<span style={{color: Colors.textColor, fontSize: 72, fontWeight: "bold"}}> 
```

Ich bin mir noch nicht sicher, was die Idee dahinter ist, würde aber vorschlagen für sowas Klassen zu nutzen und eine separate CSS-Datei anzulegen.

**Comment by uwap** [comment]
Grundsätzlich ist der Vorteil von inline styles erst mal, dass man den Zustandsabhängig im Javascript ändern kann. Aber ich stimme zu, dass sich da gerade vieles doppelt. Gerade so zeug wie die styles für buttons, font sizes an vielen stellen etc. sollten wir in eine CSS Datei auslagern.
