### ISSUE TITLE
Instead of using coinbase as exchange add a local exchange account

### ISSUE THREAD

**Issue by stp-ip** [silsha/fnordcredit#52]
Let users add bitcoins as credit #51 
On purchase exchange use the current exchange rate + x% to exchange bitcoins for € and pay for the good. This would be achieved via a local exchange account with both bitcoins and € in it's account.
The coins would go to the set bitcoin wallet for this exchange account.

**Comment by uwap** [comment]
We are hipsters, but not THAT hipster.
