### ISSUE TITLE
User name sorting bug

### ISSUE THREAD

**Issue by tabascoeye** [silsha/fnordcredit#57]
When a user enters a space character as first char, it gets sorted to the front of the list when doing an alphabetical sort.

We should either deny usernames with spaces in front or make the sorting algorithm ignore whitespace in front.

**Comment by uwap** [comment]
I think this is a social problem rather than a technical problem. If people want to be the first in alphabetic search they could achieve this either way. I prefer people calling themselves " name" than "aaaaaaa name"
